AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  AlexaLambdaHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: alexa_handler.lambda_handler
      Runtime: python3.6
      CodeUri: src/
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
